/-
Copyright (c) 2026 AxiomMath. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Axiom Math
-/
import Mathlib.Analysis.Fourier.FiniteAbelian.PontryaginDuality
import Mathlib.GroupTheory.SpecificGroups.Dihedral
import Lyons.Meta.Tag

/-!
# Characters, pointwise powers, and the dihedral generators

Three notions this development uses but does not build, because Mathlib has
them: the character group of a finite abelian group, the pointwise power of a
`ℂ`-valued function, and the two distinguished elements of a dihedral group.

None of the three introduces a new object.

* `Lyons.charGroup` is an `abbrev`, hence reducible. It elaborates to
  `AddChar A ℂ`, and every consumer continues to see, unfold and rewrite with
  `AddChar`; there is no second notion of "character group".
* Mathlib's `Pi.instPow` already *is* the pointwise power, so its content — the
  defining equation `f^m a = (f a)^m` — is stated as a lemma about it.
* The dihedral generators are Mathlib's own `DihedralGroup.r 1` and
  `DihedralGroup.sr 0`: `r` is a rotation of order `n` generating the index-two
  cyclic subgroup and `b` lies outside it, and that content is stated about
  those two elements directly.

## Additive characters valued in `ℂ` rather than in `ℂˣ`

The group `A` is written additively throughout, so its dual is `AddChar A ℂ` —
additive characters, valued in the *monoid* `ℂ` rather than in the units `ℂˣ`.

For a **finite** `A` the two agree: every value of an additive character on a
finite group is a root of unity, since
`ψ a ^ Fintype.card A = ψ (card A • a) = ψ 0 = 1`, hence nonzero, so a character
valued in `ℂ` lands in `ℂˣ` automatically and the two groups are the same group.
Finiteness is a standing hypothesis everywhere the dual is used.
`Lyons.charGroup_apply_ne_zero` below records this, and it is the content of the
identification.
-/

namespace Lyons

open Finset

/-! ### The character group -/

/-- The **character group** `Â` of a finite abelian group, written additively.

A reducible abbreviation for Mathlib's `AddChar A ℂ`, deliberately: see the
module docstring for the identification of `ℂ`-valued with `ℂˣ`-valued
characters. -/
@[lyons_tag "def_char_group"]
abbrev charGroup (A : Type*) [AddCommGroup A] : Type _ := AddChar A ℂ

/-- **Characters of a finite group never vanish**, so `AddChar A ℂ` really is the
group of homomorphisms into `ℂˣ`.

A character's values are roots of unity, hence units. -/
theorem charGroup_apply_ne_zero {A : Type*} [AddCommGroup A] [Fintype A]
    (ψ : charGroup A) (a : A) : ψ a ≠ 0 := by
  intro h
  have hne : Fintype.card A ≠ 0 := Fintype.card_ne_zero
  have hpow : (ψ a) ^ Fintype.card A = 1 := by
    rw [← AddChar.map_nsmul_eq_pow, card_nsmul_eq_zero, AddChar.map_zero_eq_one]
  rw [h, zero_pow hne] at hpow
  exact zero_ne_one hpow

/-! ### The pointwise power -/

/-- The **pointwise power** `f^m a = (f a)^m`.

No new object: `Pi.instPow` already gives `f ^ m` its pointwise meaning, so all
there is to say is this defining equation, which holds by `rfl`. Stated for a
general monoid codomain rather than for `ℂ`, and for `m : ℕ` rather than for
integers `m ≥ 1`, since `Monoid.npow` is what the consumers use. -/
@[lyons_tag "def_pointwise_power"]
theorem pi_pow_apply {A : Type*} {M : Type*} [Monoid M] (f : A → M) (m : ℕ)
    (a : A) : (f ^ m) a = (f a) ^ m := rfl

/-! ### The dihedral generators -/

section Dihedral

variable {n : ℕ} [NeZero n]

/-- **`r` is a rotation of order `n`**, stated about Mathlib's
`DihedralGroup.r 1` rather than about a fresh name for it. -/
@[lyons_tag "not_dihedral_gens"]
theorem orderOf_dihedral_r_one : orderOf (DihedralGroup.r 1 : DihedralGroup n) = n :=
  DihedralGroup.orderOf_r_one

/-- **`b` lies outside the cyclic subgroup generated by `r`.** The element
`DihedralGroup.sr 0` is not a rotation, and the subgroup generated by `r 1`
consists exactly of the rotations. -/
@[lyons_tag "not_dihedral_gens"]
theorem dihedral_sr_zero_notMem_zpowers_r_one :
    (DihedralGroup.sr 0 : DihedralGroup n) ∉ Subgroup.zpowers (DihedralGroup.r 1) := by
  intro hmem
  obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hmem
  rw [DihedralGroup.r_one_zpow] at hk
  simp at hk

/-! ### The dihedral normal form and relations

Mathlib presents `D_n` by the two constructors `DihedralGroup.r` and
`DihedralGroup.sr`, each indexed by `ZMod n`, so the normal form *is* the
defining case distinction and the relations are entries of the multiplication
table. -/

/-- **Dihedral normal form.** Every element of `D_n` is exactly one of `r j` or
`sr j`, and each indexing is injective.

Uniqueness is constructor disjointness (`r j ≠ sr k`), which is what the
`Sum`-shaped equivalence below packages; injectivity on each half is constructor
injectivity. -/
@[lyons_tag "lem_ext_normal_form"]
def dihedralSumEquiv : ZMod n ⊕ ZMod n ≃ DihedralGroup n where
  toFun x := Sum.elim DihedralGroup.r DihedralGroup.sr x
  invFun g := match g with
    | DihedralGroup.r j => Sum.inl j
    | DihedralGroup.sr j => Sum.inr j
  left_inv x := by cases x <;> rfl
  right_inv g := by cases g <;> rfl

/-- **Dihedral relations.** `r^n = 1`, `b² = 1`, and `b r b = r⁻¹`, where
`b = sr 0`.

Each is read off Mathlib's multiplication table. `r^n = 1` is `orderOf_r_one`
turned into a power identity; the other two are `simp` on `sr_mul_sr` and
`sr_mul_r` / `r_mul_sr`. -/
@[lyons_tag "lem_ext_relations"]
theorem dihedral_relations (j : ZMod n) :
    (DihedralGroup.r 1 : DihedralGroup n) ^ n = 1 ∧
      (DihedralGroup.sr 0 : DihedralGroup n) * DihedralGroup.sr 0 = 1 ∧
      (DihedralGroup.sr 0 : DihedralGroup n) * DihedralGroup.r j
          * DihedralGroup.sr 0 = (DihedralGroup.r j)⁻¹ := by
  refine ⟨?_, ?_, ?_⟩
  · -- Two traps here.
    --
    -- `pow_orderOf_eq_one _` leaves the element a metavariable, so the
    -- `Monoid`/`Finite` instance search has nothing to resolve and reports
    -- "typeclass instance problem is stuck". Hence the explicit element.
    --
    -- And `rw [← DihedralGroup.orderOf_r_one]` does NOT work. That lemma is
    -- `orderOf (r 1) = n`, so rewriting it backwards replaces `n` — but `n` also
    -- occurs in the *type* `DihedralGroup n`, and the type occurrence is hit
    -- first, giving a type mismatch. Rewrite forwards in a hypothesis instead,
    -- where the thing replaced is `orderOf (r 1)` and no type mentions it.
    have h := pow_orderOf_eq_one (DihedralGroup.r 1 : DihedralGroup n)
    rwa [DihedralGroup.orderOf_r_one] at h
  · simp
  · -- `sr 0 * r j = sr (0 + j) = sr j`, then `sr j * sr 0 = r (0 - j) = r (-j)`,
    -- which is `(r j)⁻¹`. Mathlib's table is `sr i * r j = sr (i + j)` and
    -- `sr i * sr j = r (j - i)`.
    simp

end Dihedral

end Lyons
