/-
Copyright (c) 2026 AxiomMath. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Axiom Math
-/
import Lyons.Objective.RateMonotonic
import Lyons.Walk.Relabel

/-!
# Transporting rate-monotonicity along an isomorphism

These lemmas are what carry rate-monotonicity from the inversion extension over
to the dihedral group: `D_n` and `G_{ℤ/n, 0}` are two descriptions of one group,
so in Lean they are two *different* objects and the conclusion has to be moved
across the isomorphism `Lyons.InvExt.dihedralEquiv`.

## Where the two levels meet

`Lyons.RateMonotonic` quantifies over rate *collections* — arbitrary
`G → ℝ` satisfying `Lyons.IsSymmRate` — while the analysis is done on `RateFn`,
which additionally forces the value `0` at the identity. `Lyons.IsSymmRate.comp`
relabels a collection and `Lyons.IsSymmRate.toRateFn_comp` says that discarding
the identity rate commutes with relabelling, since an isomorphism sends `1` to
`1`. That is the only interaction between the two levels here.

## Main results

* `Lyons.IsSymmRate.comp` : a relabelled collection is symmetric.
* `Lyons.Generating.comp` : a relabelled collection is generating.
* `Lyons.distToUniform_comp` : the distance to stationarity is unchanged by a
  relabelling.
* `Lyons.RateMonotonic.of_mulEquiv` : rate-monotonicity transports along an
  isomorphism.
-/

open Finset

namespace Lyons

variable {G H : Type*} [Group G] [Group H]

/-- The relabelled rate collection `λ^φ`, with `λ^φ h = λ (φ h)`. This is the
level of collections; `Lyons.RateFn.comp` is the same operation on rate
functions. -/
theorem IsSymmRate.comp {lam : G → ℝ} (hlam : IsSymmRate lam) (φ : H ≃* G) :
    IsSymmRate fun h : H => lam (φ h) where
  nonneg h := hlam.nonneg _
  symm h := by rw [map_inv, hlam.symm]

/-- **A relabelled rate collection is generating.**

The support of `λ^φ` is `φ⁻¹` of the support of `λ`, and an isomorphism carries
the subgroup generated by a set to the subgroup generated by its image; so the
closure of the one support is `⊤` exactly when the closure of the other is. -/
@[lyons_tag "lem_rate_comp_generating"]
theorem Generating.comp {lam : G → ℝ} (hgen : Generating lam) (φ : H ≃* G) :
    Generating fun h : H => lam (φ h) := by
  have himg : (fun g : G => φ.symm g) '' {g : G | 0 < lam g}
      = {h : H | 0 < lam (φ h)} := by
    ext h
    simp only [Set.mem_image, Set.mem_ofPred_eq]
    refine ⟨fun ⟨g, hg, hgh⟩ => ?_, fun hh => ⟨φ h, hh, φ.symm_apply_apply h⟩⟩
    rw [← hgh, MulEquiv.apply_symm_apply]
    exact hg
  have h1 : Subgroup.map φ.symm.toMonoidHom (Subgroup.closure {g : G | 0 < lam g})
      = Subgroup.closure {h : H | 0 < lam (φ h)} := by
    rw [MonoidHom.map_closure, ← himg]
    rfl
  rw [Generating, ← h1, hgen]
  exact Subgroup.map_top_of_surjective _ φ.symm.surjective

variable [DecidableEq G] [DecidableEq H]

/-- Discarding the identity rate commutes with relabelling: an isomorphism sends
`1` to `1`, so the two constructions agree at every point. -/
theorem IsSymmRate.toRateFn_comp {lam : G → ℝ} (hlam : IsSymmRate lam)
    (φ : H ≃* G) : (hlam.comp φ).toRateFn = hlam.toRateFn.comp φ := by
  refine DFunLike.ext _ _ fun h => ?_
  rw [RateFn.comp_apply, IsSymmRate.toRateFn_apply, IsSymmRate.toRateFn_apply]
  have hiff : φ h = 1 ↔ h = 1 := map_eq_one_iff φ.toMonoidHom φ.injective
  by_cases hh : h = 1
  · rw [if_pos hh, if_pos (hiff.mpr hh)]
  · rw [if_neg hh, if_neg (fun hcon => hh (hiff.mp hcon))]

variable [Fintype G] [Fintype H]

set_option linter.unusedDecidableInType false in
/-- **The distance to stationarity is unchanged by a relabelling.**

The transition function transports by `Lyons.heatCoeffReal_comp`, the two groups
have the same cardinality because `φ` is a bijection, and the sum reindexes along
it. -/
@[lyons_tag "lem_dist_relabel"]
theorem distToUniform_comp (lam : RateFn G) (φ : H ≃* G) (p t : ℝ) :
    distToUniform p (lam.comp φ) t = distToUniform p lam t := by
  have hcard : Fintype.card H = Fintype.card G := Fintype.card_congr φ.toEquiv
  rw [distToUniform, distToUniform, hcard]
  congr 1
  refine Fintype.sum_equiv φ.toEquiv _ _ fun h => ?_
  rw [heatCoeffReal_comp]
  rfl

set_option linter.unusedDecidableInType false in
/-- **Rate-monotonicity transports along an isomorphism.**

Given `φ : H ≃* G` and rate collections on `H`, push them to `G` along `φ⁻¹`,
apply rate-monotonicity of `G` there, and pull the two distances back with
`Lyons.distToUniform_comp`. The relabelling of a relabelling collapses because
`φ⁻¹ ∘ φ` is the identity, which is what makes the round trip land back on the
collections one started with. -/
@[lyons_tag "lem_rate_monotonic_iso"]
theorem RateMonotonic.of_mulEquiv {p : ℝ} (φ : H ≃* G) (hG : RateMonotonic G p) :
    RateMonotonic H p := by
  intro lam' mu' hlam' hmu' hgen' hgenm' hle t ht
  -- push the two collections to `G` along `φ⁻¹`
  set lam : G → ℝ := fun g => lam' (φ.symm g) with hlamdef
  set mu : G → ℝ := fun g => mu' (φ.symm g) with hmudef
  have hlam : IsSymmRate lam := hlam'.comp φ.symm
  have hmu : IsSymmRate mu := hmu'.comp φ.symm
  have hgen : Generating lam := hgen'.comp φ.symm
  have hgenm : Generating mu := hgenm'.comp φ.symm
  have hstep := hG lam mu hlam hmu hgen hgenm (fun g => hle _) t ht
  -- relabelling back along `φ` recovers the original collections
  have hback : ∀ (nu' : H → ℝ) (hnu' : IsSymmRate nu') (hnu : IsSymmRate
      fun g : G => nu' (φ.symm g)),
      hnu.toRateFn.comp φ = hnu'.toRateFn := by
    intro nu' hnu' hnu
    refine DFunLike.ext _ _ fun h => ?_
    rw [RateFn.comp_apply, IsSymmRate.toRateFn_apply, IsSymmRate.toRateFn_apply]
    have hiff : φ h = 1 ↔ h = 1 := map_eq_one_iff φ.toMonoidHom φ.injective
    by_cases hh : h = 1
    · rw [if_pos (hiff.mpr hh), if_pos hh]
    · rw [if_neg (fun hcon => hh (hiff.mp hcon)), if_neg hh, φ.symm_apply_apply]
  rw [← hback lam' hlam' hlam, ← hback mu' hmu' hmu, distToUniform_comp,
    distToUniform_comp]
  exact hstep

/-! ### Transporting a *failure*

`RateMonotonic.of_mulEquiv` is stated in one direction only, and one direction is
all that either theorem needs. `rateMonotonic_dihedral_even` instantiates it with
`G` the inversion extension and `H = D_n`, along `InvExt.dihedralEquiv.symm`,
moving an *assertion* of rate-monotonicity onto the dihedral group.
`not_rateMonotonic_dihedral_of_not_even` has to move a *failure* the other way,
and that is the same lemma along the same isomorphism, contraposed. So the two
theorems use `RateMonotonic.of_mulEquiv` and `InvExt.dihedralEquiv` in opposite
directions, and neither needs a second transport lemma. -/

/-- **A failure of rate-monotonicity transports backwards along an
isomorphism.**

The contrapositive of `Lyons.RateMonotonic.of_mulEquiv`: if `H` is not
rate-monotonic and `φ : H ≃* G`, then `G` is not either. Stated at this
generality rather than for the dihedral case alone, since nothing in it looks at
the two groups. -/
theorem not_rateMonotonic_of_mulEquiv {p : ℝ} (φ : H ≃* G)
    (hH : ¬ RateMonotonic H p) : ¬ RateMonotonic G p :=
  fun hG => hH (RateMonotonic.of_mulEquiv φ hG)

end Lyons
